version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: docker-config/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    command: npx nodemon server.js --legacy-watch
